# -*- coding: utf-8 -*-
"""online amazon price tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5maTW8aHp1BJYfSVj0VF40t65a0rqds

## Product Price Alert System: Customized Price Monitoring for Smarter Shopping  

Our code simplifies the process of monitoring product prices on Amazon and sends you an email alert when the product price meets or drops below your **customized target price**. Unlike most websites that notify you of general price drops without tailoring to your specific budget, our solution allows you to define the exact price you’re willing to pay.  

For example, if you wish to purchase a product only when its price is ₹XXX, our system will track the product's price and notify you immediately once it matches or falls below your desired amount. This ensures you get timely alerts, helping you purchase products faster and at the best possible price, without overpaying or missing out on deals.  

Please note that **this code is designed to work only for Amazon products**. If you're looking to track prices on other websites, you may need to adapt the code to suit the structure of those websites.  

By leveraging this code, you can:  
1. **Save time and effort** by automating price monitoring.  
2. **Get highly specific alerts** based on your budget preferences.  
3. **Act quickly** to secure products at the most competitive prices.  

This tool is ideal for budget-conscious shoppers who want full control over their price alerts, ensuring smarter and more cost-effective purchases on Amazon.

## Importing Libraries
"""

! pip install requests beautifulsoup4

"""## Installing Necessary Libraries"""

import requests as r
import bs4
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

"""## Defining the Price Tracking Function"""

def find_you_prodect_price(user_agent,your_email,your_email_password,recipients_email,prodect_url,target_price):



  def get_amazon_price(url):
      headers = {
        'user-agent': user_agent
      }
      product_response = r.get(url, headers=headers)
      soup = bs4.BeautifulSoup(product_response.text, 'lxml')
      price_whole = soup.find(class_='a-price-whole')
      price_fraction = soup.find(class_='a-price-fraction')
      if price_whole and price_fraction:
          final_price = price_whole.text + price_fraction.text
          return float(final_price.replace(',', '').strip())
      else:
          return None



  def send_email(subject, body, to_email):
      from_email = your_email
      from_password = your_email_password
      msg = MIMEMultipart()
      msg['From'] = from_email
      msg['To'] = to_email
      msg['Subject'] = subject
      msg.attach(MIMEText(body, 'plain'))
      try:
          server = smtplib.SMTP('smtp.gmail.com', 587)
          server.starttls()
          server.login(from_email, from_password)
          text = msg.as_string()
          server.sendmail(from_email, to_email, text)
          server.quit()
          print("Email sent successfully!")
      except Exception as e:
          print(f"Failed to send email: {e}")


  url = prodect_url
  desired_price = target_price

  to_email = recipients_email



  while True:
      price = get_amazon_price(url)
      print(price)
      if price is not None:
          print(f"The current price is: {price}")
          if price <= desired_price:
              send_email(
                  subject="Price Alert: Product Price Dropped",
                  body=f"The price of the product has dropped to {price}. Check the product here: {url}",
                  to_email=to_email
              )
              break
      else:
          print("Price not found")
          break

"""## Getting User Input and Running the Function"""

print('user_agent')
user_agent=input()
print('your_email')
your_email=input()
print('your_email_password')
your_email_password=input()
print('recipients_email')
recipients_email=input()
print('prodect_url')
prodect_url=input()
print('target_price')
target_price=int(input())
find_you_prodect_price(user_agent,your_email,your_email_password,recipients_email,prodect_url,target_price)

"""How to find USER AGENT:  
   1.Open your web browser (e.g., Chrome, Firefox, Edge).

 2.Right-click anywhere on the page and select Inspect or Inspect Element (Ctrl + Shift + I).
3.Go to the Network tab.

4.Refresh the page (F5).

5.Click on any network request, and under the Headers section, you will see a User-Agent header.

6.This is the user-agent string for your browser.

How to find your_email_password:

1.Go to your Google Account Security Settings.

2.Turn on 2-Step Verification if it's not already enabled.

3.Under the "Signing in to Google" section, click App Passwords.

4.Select the app and device you want to use (e.g., "Mail" and "Other (Custom)").

5.Generate an app-specific password. Copy this password and use it in your script instead of your actual password.
"""